(() => {
  const NS = 'http://www.w3.org/2000/svg';
  const SQRT3 = Math.sqrt(3);
  let renderId = 0;

  const palette = {board:'#0d1211',cell:'#232c29',cellLine:'#414b47',brass:'#d3a348',brassDark:'#6a5124',metal:'#e6dcc5',shadow:'#050807'};
  const atomGeometries = {masterAtomV1:{outerCasingRadius:24,bevelRadius:22.65,innerCasingRadius:20.15,coreRadius:18.7,innerRingRadius:16.05,rivetOrbit:21.15,rivetRadius:.42}};
  const atomMaterials = {masterMaterialV1:{gradient:{cx:'46%',cy:'28%',r:'88%'},stopLevels:[1,.89,.63,.43,.25,.12,.045],stopOffsets:['0%','10%','27%','49%','72%','89%','100%'],reflection:'masterGlassMetal'}};
  const atomIdentities = {
    Pb:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#73878a',ink:'#f5f5ef',mark:'♄',symbolSize:24.2,symbolX:0,symbolY:.2,symbolOpacity:.95},
    Sn:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#969477',ink:'#f5f1dc',mark:'♃',symbolSize:23.8,symbolX:.3,symbolY:.1,symbolOpacity:.94},
    Fe:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#806f73',ink:'#fff5ef',mark:'♂',symbolSize:26.6,symbolX:.2,symbolY:.5,symbolOpacity:.96},
    Cu:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#b66f48',ink:'#fff0e5',mark:'♀',symbolSize:26.3,symbolX:0,symbolY:.8,symbolOpacity:.96},
    Ag:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#bfc4c1',ink:'#fff',mark:'☽',symbolSize:27.2,symbolX:1,symbolY:-.2,symbolOpacity:.96},
    Au:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#c39a3f',ink:'#fff4c2',mark:'☉',symbolSize:23.8,symbolX:0,symbolY:.2,symbolOpacity:.96},
    Hg:{geometry:'masterAtomV1',material:'masterMaterialV1',color:'#b7b09a',gradientStops:['#e6e1d2','#d9d3c2','#beb7a2','#9f9885','#857f70','#625e53','#403d36'],ringTint:'#d7d2c4',innerRingTint:'#8f897a',ink:'#fff8e7',mark:'☿',symbolSize:25.8,symbolX:0,symbolY:.8,symbolOpacity:.95}
  };
  const armGeometries = {masterSimpleArmV2:{baseHexRadius:28,dialHousingRadius:18.7,goldRingRadius:15.6,dialRadius:12.7,neckStart:15.1,railHalfGap:3.05,attachmentOffset:16.2,pivotOuterRadius:6.1,pivotInnerRadius:3.05,gripRingRadius:19.2,gripRingWidth:2.9,jawWidth:4.55,footLength:8.8,footWidth:3.4}};
  const armMaterials = {masterSimpleArmV2:{baseDark:'#090b0c',baseEdge:'#80623d',baseInset:'#151819',silverEdge:'#3d4347',rivet:'#850d64'}};

  const el=(name,attrs={})=>{const node=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));return node;};
  const axial=(q,r,size,ox,oy)=>({x:ox+size*SQRT3*(q+r/2),y:oy+size*1.5*r});
  const hexPoints=(cx,cy,size)=>Array.from({length:6},(_,i)=>{const a=Math.PI/180*(60*i-30);return `${cx+size*Math.cos(a)},${cy+size*Math.sin(a)}`}).join(' ');
  function shade(hex,factor){const value=parseInt(hex.slice(1),16);const channels=[(value>>16)&255,(value>>8)&255,value&255].map(n=>Math.max(0,Math.min(255,Math.round(n*factor))));return `#${channels.map(n=>n.toString(16).padStart(2,'0')).join('')}`;}

  function defs(svg,id){
    const d=el('defs');
    const shadow=el('filter',{id:`shadow-${id}`,x:'-50%',y:'-50%',width:'200%',height:'200%'});shadow.appendChild(el('feDropShadow',{dx:0,dy:1.8,stdDeviation:2.05,'flood-color':'#000','flood-opacity':.64}));d.appendChild(shadow);
    const atomShadow=el('filter',{id:`atom-shadow-${id}`,x:'-55%',y:'-55%',width:'210%',height:'220%'});atomShadow.appendChild(el('feDropShadow',{dx:0,dy:2.8,stdDeviation:2.65,'flood-color':'#000','flood-opacity':.78}));d.appendChild(atomShadow);
    const bevel=el('linearGradient',{id:`bevel-${id}`,x1:'8%',y1:'4%',x2:'92%',y2:'96%'});[['0%','#d9c19b'],['18%','#9a7650'],['47%','#46362a'],['73%','#ad8860'],['100%','#30251e']].forEach(([offset,color])=>bevel.appendChild(el('stop',{offset,'stop-color':color})));d.appendChild(bevel);
    const armSilver=el('linearGradient',{id:`arm-silver-${id}`,x1:'0%',y1:'0%',x2:'0%',y2:'100%'});[['0%','#f4f5f4'],['22%','#d1d4d4'],['50%','#858b8e'],['77%','#c9cdce'],['100%','#4e5458']].forEach(([offset,color])=>armSilver.appendChild(el('stop',{offset,'stop-color':color})));d.appendChild(armSilver);
    const armGold=el('radialGradient',{id:`arm-gold-${id}`,cx:'40%',cy:'32%',r:'70%'});[['0%','#fffbe7'],['30%','#eadca8'],['66%','#a9935c'],['100%','#5f5234']].forEach(([offset,color])=>armGold.appendChild(el('stop',{offset,'stop-color':color})));d.appendChild(armGold);
    const armDial=el('radialGradient',{id:`arm-dial-${id}`,cx:'42%',cy:'30%',r:'72%'});[['0%','#b945c2'],['35%','#751a81'],['72%','#42094c'],['100%','#1d0322']].forEach(([offset,color])=>armDial.appendChild(el('stop',{offset,'stop-color':color})));d.appendChild(armDial);
    const material=atomMaterials.masterMaterialV1;Object.entries(atomIdentities).forEach(([key,identity])=>{const radial=el('radialGradient',{id:`atom-${key}-${id}`,...material.gradient});material.stopOffsets.forEach((offset,index)=>radial.appendChild(el('stop',{offset,'stop-color':identity.gradientStops?.[index]||shade(identity.color,material.stopLevels[index])})));d.appendChild(radial);});
    svg.appendChild(d);
  }

  function drawBoard(svg,scene){if(scene.board?.visible===false)return;const {cols=8,rows=5,size=42,offsetX=66,offsetY=55}=scene.board||{};const g=el('g');for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){const p=axial(q,r,size,offsetX,offsetY);g.appendChild(el('polygon',{points:hexPoints(p.x,p.y,size-2),fill:palette.cell,stroke:palette.cellLine,'stroke-width':1.1,opacity:.72}));}svg.appendChild(g);}
  function drawMaterialReflections(body){[['-4.6','-6.4','6','2.45','.075','-18'],['-1.5','-8','7.3','3','.12','-12'],['2.6','-4.9','9.1','5.1','.055','-20'],['5','3.4','10.9','7.6','.022','-24']].forEach(([cx,cy,rx,ry,opacity,rot])=>body.appendChild(el('ellipse',{cx,cy,rx,ry,fill:'#fff',opacity,transform:`rotate(${rot})`})));body.appendChild(el('ellipse',{cx:-6.2,cy:3.8,rx:7.4,ry:10.8,fill:'#000',opacity:.2,transform:'rotate(14)'}));body.appendChild(el('ellipse',{cx:3.6,cy:8.8,rx:12,ry:5.3,fill:'#000',opacity:.24,transform:'rotate(-7)'}));}
  function drawIdentity(g,identity){const t=el('text',{x:identity.symbolX||0,y:identity.symbolY||0,'text-anchor':'middle','dominant-baseline':'middle','font-family':'Noto Serif Symbols 2, Segoe UI Symbol, DejaVu Sans, serif','font-size':identity.symbolSize,'font-weight':300,fill:identity.ink,'text-rendering':'geometricPrecision','pointer-events':'none',opacity:identity.symbolOpacity});t.textContent=identity.mark;g.appendChild(t);}
  function drawAtom(svg,item,scene,id){const p=axial(item.q,item.r,scene.board.size,scene.board.offsetX,scene.board.offsetY),element=String(item.element||'Fe'),identity=atomIdentities[element]||atomIdentities.Fe,geometry=atomGeometries[identity.geometry],g=el('g',{transform:`translate(${p.x} ${p.y})`,'data-atom':element}),body=el('g',{filter:`url(#atom-shadow-${id})`});body.appendChild(el('circle',{r:geometry.outerCasingRadius,fill:'#090908',stroke:'#201a17','stroke-width':.96}));body.appendChild(el('circle',{r:geometry.bevelRadius,fill:`url(#bevel-${id})`,stroke:'#2f241d','stroke-width':.7}));body.appendChild(el('circle',{r:geometry.innerCasingRadius,fill:'#111513',stroke:'#070909','stroke-width':.76}));body.appendChild(el('circle',{r:geometry.coreRadius,fill:`url(#atom-${element}-${id})`,stroke:identity.ringTint||shade(identity.color,1.35),'stroke-width':.5}));body.appendChild(el('circle',{r:geometry.innerRingRadius,fill:'none',stroke:identity.innerRingTint||shade(identity.color,.3),'stroke-width':.72,opacity:.58}));drawMaterialReflections(body);for(let i=0;i<6;i++){const a=i*Math.PI/3;body.appendChild(el('circle',{cx:geometry.rivetOrbit*Math.cos(a),cy:geometry.rivetOrbit*Math.sin(a),r:geometry.rivetRadius,fill:'#3a3027',stroke:'#b99d70','stroke-width':.2,opacity:.46}));}g.appendChild(body);drawIdentity(g,identity);svg.appendChild(g);}

  function drawArm(svg,item,scene,id){
    const p=axial(item.q,item.r,scene.board.size,scene.board.offsetX,scene.board.offsetY);
    const rotation=((Number(item.rotation)||0)%6+6)%6,angle=rotation*60,length=Math.max(1,Math.min(3,Number(item.length)||1));
    const targetDistance=length*scene.board.size*SQRT3,geo=armGeometries.masterSimpleArmV2,mat=armMaterials.masterSimpleArmV2;
    const gripX=targetDistance,pivotX=gripX-geo.gripRingRadius+geo.attachmentOffset,railEnd=pivotX-geo.pivotOuterRadius+.4;
    const g=el('g',{transform:`translate(${p.x} ${p.y}) rotate(${angle})`,'data-arm':'simple','data-length':length,'data-rotation':rotation,'data-target-distance':targetDistance,'data-geometry':'masterSimpleArmV2'}),body=el('g',{filter:`url(#shadow-${id})`});
    body.appendChild(el('polygon',{points:hexPoints(0,0,geo.baseHexRadius),fill:mat.baseDark,stroke:mat.baseEdge,'stroke-width':1.05}));body.appendChild(el('polygon',{points:hexPoints(0,0,geo.baseHexRadius-3),fill:mat.baseInset,stroke:'#050606','stroke-width':.9}));
    const neck=`M${geo.neckStart},-8.9 C${geo.neckStart+7},-7.2 ${geo.neckStart+10},-${geo.railHalfGap} ${geo.neckStart+17},-${geo.railHalfGap} L${railEnd},-${geo.railHalfGap} L${railEnd},${geo.railHalfGap} L${geo.neckStart+17},${geo.railHalfGap} C${geo.neckStart+10},${geo.railHalfGap} ${geo.neckStart+7},7.2 ${geo.neckStart},8.9 Z`;
    body.appendChild(el('path',{d:neck,fill:'#383e42',stroke:'#24282b','stroke-width':1.35}));body.appendChild(el('path',{d:neck,fill:`url(#arm-silver-${id})`,stroke:'#eef0ef','stroke-width':.52,transform:'scale(.976 .84) translate(.35 0)'}));
    body.appendChild(el('circle',{r:geo.dialHousingRadius,fill:`url(#arm-silver-${id})`,stroke:mat.silverEdge,'stroke-width':1.05}));body.appendChild(el('circle',{r:geo.goldRingRadius,fill:'#d7c68a',stroke:'#766842','stroke-width':.95}));body.appendChild(el('circle',{r:geo.dialRadius,fill:`url(#arm-dial-${id})`,stroke:'#310538','stroke-width':1.15}));body.appendChild(el('circle',{r:geo.dialRadius-3.1,fill:'none',stroke:'#da62dc','stroke-width':.9,opacity:.36}));
    body.appendChild(el('circle',{cx:pivotX,cy:0,r:geo.pivotOuterRadius,fill:`url(#arm-gold-${id})`,stroke:'#746641','stroke-width':.9}));body.appendChild(el('circle',{cx:pivotX,cy:0,r:geo.pivotInnerRadius,fill:'#fffbe5',stroke:'#cabb83','stroke-width':.55}));
    for(const a of [0,120,240]){const rad=a*Math.PI/180,x1=gripX+Math.cos(rad)*(geo.gripRingRadius+.7),y1=Math.sin(rad)*(geo.gripRingRadius+.7),x2=gripX+Math.cos(rad)*(geo.gripRingRadius+geo.footLength),y2=Math.sin(rad)*(geo.gripRingRadius+geo.footLength);body.appendChild(el('path',{d:`M${x1},${y1} L${x2},${y2}`,stroke:'#303539','stroke-width':geo.footWidth+2.2,'stroke-linecap':'round'}));body.appendChild(el('path',{d:`M${x1},${y1} L${x2},${y2}`,stroke:`url(#arm-silver-${id})`,'stroke-width':geo.footWidth,'stroke-linecap':'round'}));}
    body.appendChild(el('circle',{cx:gripX,cy:0,r:geo.gripRingRadius,fill:'none',stroke:'#34393d','stroke-width':geo.gripRingWidth+1.7}));body.appendChild(el('circle',{cx:gripX,cy:0,r:geo.gripRingRadius,fill:'none',stroke:`url(#arm-silver-${id})`,'stroke-width':geo.gripRingWidth}));
    const jaw=`M${pivotX-.3},-6.5 C${pivotX+4.8},-14.2 ${gripX-9.2},-${geo.gripRingRadius+1.9} ${gripX+.6},-${geo.gripRingRadius+.4} A${geo.gripRingRadius+.4},${geo.gripRingRadius+.4} 0 0 0 ${pivotX-.3},6.5`;
    body.appendChild(el('path',{d:jaw,fill:'none',stroke:'#303539','stroke-width':geo.jawWidth+1.7,'stroke-linecap':'round'}));body.appendChild(el('path',{d:jaw,fill:'none',stroke:`url(#arm-silver-${id})`,'stroke-width':geo.jawWidth,'stroke-linecap':'round'}));body.appendChild(el('circle',{cx:pivotX+1.15,cy:-7.9,r:1.75,fill:mat.rivet,stroke:'#3b102f','stroke-width':.65}));
    const labelGroup=el('g',{transform:`rotate(${-angle})`}),label=el('text',{x:0,y:.7,'text-anchor':'middle','dominant-baseline':'middle','font-family':'Georgia, Times New Roman, serif','font-size':16.5,'font-weight':700,fill:'#fffdf4',stroke:'#251f27','stroke-width':.5,'paint-order':'stroke','pointer-events':'none'});label.textContent=String(length);labelGroup.appendChild(label);body.appendChild(labelGroup);
    g.appendChild(body);svg.appendChild(g);
  }

  function drawProjection(svg,item,scene){const p=axial(item.q,item.r,scene.board.size,scene.board.offsetX,scene.board.offsetY),g=el('g',{transform:`translate(${p.x} ${p.y})`});g.appendChild(el('circle',{r:29,fill:palette.shadow,stroke:palette.brass,'stroke-width':5}));g.appendChild(el('circle',{r:21,fill:'none',stroke:palette.metal,'stroke-width':3}));g.appendChild(el('circle',{r:11,fill:'#8c236d',stroke:'#f0b7df','stroke-width':3}));for(let i=0;i<4;i++)g.appendChild(el('path',{d:'M0,-38 L6,-27 L-6,-27 Z',fill:palette.metal,transform:`rotate(${i*90})`}));svg.appendChild(g);}
  function drawBonding(svg,item,scene){const p=axial(item.q,item.r,scene.board.size,scene.board.offsetX,scene.board.offsetY),g=el('g',{transform:`translate(${p.x} ${p.y})`});g.appendChild(el('circle',{r:28,fill:palette.shadow,stroke:palette.brass,'stroke-width':4}));g.appendChild(el('path',{d:'M-12,-9 L0,0 L12,-9 M-12,9 L0,0 L12,9',fill:'none',stroke:palette.metal,'stroke-width':4,'stroke-linecap':'round'}));svg.appendChild(g);}
  function drawTrack(svg,item,scene){const a=axial(item.q1,item.r1,scene.board.size,scene.board.offsetX,scene.board.offsetY),b=axial(item.q2,item.r2,scene.board.size,scene.board.offsetX,scene.board.offsetY);svg.appendChild(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:palette.brassDark,'stroke-width':12,'stroke-linecap':'round'}));svg.appendChild(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:palette.metal,'stroke-width':3,'stroke-dasharray':'8 8','stroke-linecap':'round'}));}
  function render(scene){const width=scene.width||720,height=scene.height||360,id=++renderId;scene.board={cols:8,rows:5,size:42,offsetX:66,offsetY:55,...scene.board};const svg=el('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':scene.label||'Opus Magnum scene'});defs(svg,id);svg.appendChild(el('rect',{width,height,fill:palette.board}));drawBoard(svg,scene);(scene.tracks||[]).forEach(x=>drawTrack(svg,x,scene));(scene.glyphs||[]).forEach(x=>x.type==='projection'?drawProjection(svg,x,scene):x.type==='bonding'?drawBonding(svg,x,scene):null);(scene.arms||[]).forEach(x=>drawArm(svg,x,scene,id));(scene.atoms||[]).forEach(x=>drawAtom(svg,x,scene,id));return svg.outerHTML;}
  window.OpusJS={version:'1.3.0',render,axial,primitives:{atomGeometries,atomMaterials,atomIdentities,armGeometries,armMaterials}};
})();
